
import { HeirDefinition, HeirKey } from './types';

export interface CurrencyInfo {
  code: string;
  symbol: string;
  nameEn: string;
}

export const CURRENCIES: CurrencyInfo[] = [
  { code: 'USD', symbol: '$', nameEn: 'US Dollar' },
  { code: 'EUR', symbol: '€', nameEn: 'Euro' },
  { code: 'GBP', symbol: '£', nameEn: 'British Pound' },
  { code: 'SAR', symbol: '﷼', nameEn: 'Saudi Riyal' },
  { code: 'AED', symbol: 'د.إ', nameEn: 'UAE Dirham' },
  { code: 'PKR', symbol: '₨', nameEn: 'Pakistani Rupee' },
  { code: 'INR', symbol: '₹', nameEn: 'Indian Rupee' },
  { code: 'TRY', symbol: '₺', nameEn: 'Turkish Lira' },
  { code: 'IDR', symbol: 'Rp', nameEn: 'Indonesian Rupiah' },
  { code: 'MYR', symbol: 'RM', nameEn: 'Malaysian Ringgit' },
  { code: 'EGP', symbol: 'E£', nameEn: 'Egyptian Pound' },
  { code: 'KWD', symbol: 'KD', nameEn: 'Kuwaiti Dinar' },
  { code: 'QAR', symbol: 'QR', nameEn: 'Qatari Riyal' },
  { code: 'BDT', symbol: '৳', nameEn: 'Bangladeshi Taka' },
  { code: 'NGN', symbol: '₦', nameEn: 'Nigerian Naira' },
  { code: 'ZAR', symbol: 'R', nameEn: 'South African Rand' },
  { code: 'CAD', symbol: 'C$', nameEn: 'Canadian Dollar' },
  { code: 'AUD', symbol: 'A$', nameEn: 'Australian Dollar' },
  { code: 'JPY', symbol: '¥', nameEn: 'Japanese Yen' },
  { code: 'CNY', symbol: '¥', nameEn: 'Chinese Yuan' }
];

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'ar', name: 'العربية' },
  { code: 'ur', name: 'اردو' },
  { code: 'hi', name: 'हिन्दी' },
  { code: 'bn', name: 'বাংলা' },
  { code: 'tr', name: 'Türkçe' },
  { code: 'id', name: 'Bahasa Indonesia' },
  { code: 'fr', name: 'Français' },
  { code: 'es', name: 'Español' }
];

export const MALE_HEIRS: HeirDefinition[] = [
  { id: 'son', nameEn: 'Son', nameAr: 'ابن', gender: 'M' },
  { id: 'grandson', nameEn: "Son's son", nameAr: 'ابن الابن', gender: 'M' },
  { id: 'father', nameEn: 'Father', nameAr: 'أب', gender: 'M' },
  { id: 'grandfather', nameEn: 'Paternal grandfather', nameAr: 'جد', gender: 'M' },
  { id: 'fullBrother', nameEn: 'Full brother', nameAr: 'أخ شقيق', gender: 'M' },
  { id: 'paternalBrother', nameEn: 'Paternal brother', nameAr: 'أخ لأب', gender: 'M' },
  { id: 'maternalBrother', nameEn: 'Maternal brother', nameAr: 'أخ لأم', gender: 'M' },
  { id: 'nephewFull', nameEn: 'Son of full brother', nameAr: 'ابن الأخ الشقيق', gender: 'M' },
  { id: 'nephewPaternal', nameEn: 'Son of paternal brother', nameAr: 'ابن الأخ لأب', gender: 'M' },
  { id: 'uncleFull', nameEn: 'Paternal uncle (full)', nameAr: 'عم شقيق', gender: 'M' },
  { id: 'unclePaternal', nameEn: 'Paternal uncle (paternal)', nameAr: 'عم لأب', gender: 'M' },
  { id: 'cousinFull', nameEn: 'Son of full paternal uncle', nameAr: 'ابن العم الشقيق', gender: 'M' },
  { id: 'cousinPaternal', nameEn: 'Son of paternal uncle (paternal)', nameAr: 'ابن العم لأب', gender: 'M' },
  { id: 'husband', nameEn: 'Husband', nameAr: 'زوج', gender: 'M' },
  { id: 'freedSlaveMale', nameEn: 'Freed male slave', nameAr: 'معتِق', gender: 'M' }
];

export const FEMALE_HEIRS: HeirDefinition[] = [
  { id: 'daughter', nameEn: 'Daughter', nameAr: 'بنت', gender: 'F' },
  { id: 'granddaughter', nameEn: "Son's daughter", nameAr: 'بنت الابن', gender: 'F' },
  { id: 'mother', nameEn: 'Mother', nameAr: 'أم', gender: 'F' },
  { id: 'paternalGrandmother', nameEn: 'Paternal grandmother', nameAr: 'جدة لأب', gender: 'F' },
  { id: 'maternalGrandmother', nameEn: 'Maternal grandmother', nameAr: 'جدة لأم', gender: 'F' },
  { id: 'fullSister', nameEn: 'Full sister', nameAr: 'أخت شقيقة', gender: 'F' },
  { id: 'paternalSister', nameEn: 'Paternal sister', nameAr: 'أخت لأب', gender: 'F' },
  { id: 'maternalSister', nameEn: 'Maternal sister', nameAr: 'أخت لأم', gender: 'F' },
  { id: 'wife', nameEn: 'Wife', nameAr: 'زوجة', gender: 'F' },
  { id: 'freedSlaveFemale', nameEn: 'Freed female slave', nameAr: 'معتِقة', gender: 'F' }
];

export const ALL_HEIRS = [...MALE_HEIRS, ...FEMALE_HEIRS];

const heirTranslations: Record<string, Record<HeirKey, string>> = {
  en: { son: 'Son', grandson: "Son's son", father: 'Father', grandfather: 'Grandfather', fullBrother: 'Full Brother', paternalBrother: 'Paternal Brother', maternalBrother: 'Maternal Brother', nephewFull: 'Nephew (Full)', nephewPaternal: 'Nephew (Paternal)', uncleFull: 'Uncle (Full)', unclePaternal: 'Uncle (Paternal)', cousinFull: 'Cousin (Full)', cousinPaternal: 'Cousin (Paternal)', husband: 'Husband', freedSlaveMale: 'Freed Slave (M)', daughter: 'Daughter', granddaughter: "Son's Daughter", mother: 'Mother', paternalGrandmother: 'Paternal Grandmother', maternalGrandmother: 'Maternal Grandmother', fullSister: 'Full Sister', paternalSister: 'Paternal Sister', maternalSister: 'Maternal Sister', wife: 'Wife', freedSlaveFemale: 'Freed Slave (F)', governmentTreasury: 'Bait-ul-Maal' },
  ur: { son: 'بیٹا', grandson: 'پوتا', father: 'والد', grandfather: 'دادا', fullBrother: 'سگا بھائی', paternalBrother: 'علاتی بھائی', maternalBrother: 'اخیافی بھائی', nephewFull: 'بھتیجا (سگا)', nephewPaternal: 'بھتیجا (علاتی)', uncleFull: 'چچا (سگا)', unclePaternal: 'چچا (علاتی)', cousinFull: 'چچا زاد (سگا)', cousinPaternal: 'چچا زاد (علاتی)', husband: 'شوہر', freedSlaveMale: 'آزاد کردہ غلام', daughter: 'بیٹی', granddaughter: 'پوتی', mother: 'والدہ', paternalGrandmother: 'دادی', maternalGrandmother: 'نانی', fullSister: 'سگی بہن', paternalSister: 'علاتی بہن', maternalSister: 'اخیافی بہن', wife: 'بیوی', freedSlaveFemale: 'آزاد کردہ لونڈی', governmentTreasury: 'بیت المال' },
  ar: { son: 'ابن', grandson: 'ابن ابن', father: 'أب', grandfather: 'جد', fullBrother: 'أخ شقيق', paternalBrother: 'أخ لأب', maternalBrother: 'أخ لأم', nephewFull: 'ابن أخ شقيق', nephewPaternal: 'ابن أخ لأب', uncleFull: 'عم شقيق', unclePaternal: 'عم لأب', cousinFull: 'ابن عم شقيق', cousinPaternal: 'ابن عم لأب', husband: 'زوج', freedSlaveMale: 'معتق', daughter: 'بنت', granddaughter: 'بنت ابن', mother: 'أم', paternalGrandmother: 'جدة لأب', maternalGrandmother: 'جدة لأم', fullSister: 'أخت شقيقة', paternalSister: 'أخت لأب', maternalSister: 'أخت لأم', wife: 'زوجة', freedSlaveFemale: 'معتقة', governmentTreasury: 'بيت المال' },
  hi: { son: 'बेटा', grandson: 'पोता', father: 'पिता', grandfather: 'दादा', fullBrother: 'सगा भाई', paternalBrother: 'सौतेला भाई', maternalBrother: 'सौतेला भाई (माँ)', nephewFull: 'भतीजा', nephewPaternal: 'भतीजा (सौतेला)', uncleFull: 'सगा चाचा', unclePaternal: 'सौतेला चाचा', cousinFull: 'सगा चचेरा भाई', cousinPaternal: 'सौतेला चचेरा भाई', husband: 'पति', freedSlaveMale: 'आज़ाद गुलाम', daughter: 'बेटी', granddaughter: 'पोती', mother: 'माता', paternalGrandmother: 'दादी', maternalGrandmother: 'नानी', fullSister: 'सगी बहन', paternalSister: 'सौतेली बहन', maternalSister: 'सौतेली बहन (माँ)', wife: 'पत्नी', freedSlaveFemale: 'आज़ाद दासी', governmentTreasury: 'राजकोष' },
  bn: { son: 'ছেলে', grandson: 'পৌত্র', father: 'পিতা', grandfather: 'দাদা', fullBrother: 'সহোদর ভাই', paternalBrother: 'বৈমাত্রেয় ভাই', maternalBrother: 'বৈপিত্রীয় ভাই', nephewFull: 'ভাইপো', nephewPaternal: 'ভাইপো (বৈমাত্রেয়)', uncleFull: 'চাচা', unclePaternal: 'চাচা (বৈমাত্রেয়)', cousinFull: 'চাচাতো ভাই', cousinPaternal: 'চাচাতো ভাই (বৈমাত্রেয়)', husband: 'স্বামী', freedSlaveMale: 'মুক্ত দাস', daughter: 'মেয়ে', granddaughter: 'পৌত্রী', mother: 'মাতা', paternalGrandmother: 'দাদী', maternalGrandmother: 'নানী', fullSister: 'সহোদর বোন', paternalSister: 'বৈমাত্রেয় বোন', maternalSister: 'বৈপিত্রীয় বোন', wife: 'স্ত্রী', freedSlaveFemale: 'মুক্ত দাসী', governmentTreasury: 'বাইতুল মাল' },
  tr: { son: 'Oğul', grandson: 'Torun (Erkek)', father: 'Baba', grandfather: 'Dede', fullBrother: 'Öz Erkek Kardeş', paternalBrother: 'Baba Bir Kardeş', maternalBrother: 'Anne Bir Kardeş', nephewFull: 'Yeğen (Öz)', nephewPaternal: 'Yeğen (Baba Bir)', uncleFull: 'Amca (Öz)', unclePaternal: 'Amca (Baba Bir)', cousinFull: 'Kuzen (Amca Oğlu)', cousinPaternal: 'Kuzen (Baba Bir Amca Oğlu)', husband: 'Koca', freedSlaveMale: 'Azatlı Köle (E)', daughter: 'Kız', granddaughter: 'Torun (Kız)', mother: 'Anne', paternalGrandmother: 'Babaanne', maternalGrandmother: 'Anneanne', fullSister: 'Öz Kız Kardeş', paternalSister: 'Baba Bir Kız Kardeş', maternalSister: 'Anne Bir Kız Kardeş', wife: 'Karı', freedSlaveFemale: 'Azatlı Köle (K)', governmentTreasury: 'Beytülmal' },
  id: { son: 'Anak Laki-laki', grandson: 'Cucu Laki-laki', father: 'Ayah', grandfather: 'Kakek', fullBrother: 'Saudara Kandung', paternalBrother: 'Saudara Sebapak', maternalBrother: 'Saudara Seibu', nephewFull: 'Keponakan Kandung', nephewPaternal: 'Keponakan Sebapak', uncleFull: 'Paman Kandung', unclePaternal: 'Paman Sebapak', cousinFull: 'Sepupu Kandung', cousinPaternal: 'Sepupu Sebapak', husband: 'Suami', freedSlaveMale: 'Budak Merdeka (L)', daughter: 'Anak Perempuan', granddaughter: 'Cucu Perempuan', mother: 'Ibu', paternalGrandmother: 'Nenek (Ayah)', maternalGrandmother: 'Nenek (Ibu)', fullSister: 'Saudari Kandung', paternalSister: 'Saudari Sebapak', maternalSister: 'Saudari Seibu', wife: 'Istri', freedSlaveFemale: 'Budak Merdeka (P)', governmentTreasury: 'Baitul Maal' },
  fr: { son: 'Fils', grandson: 'Petit-fils', father: 'Père', grandfather: 'Grand-père', fullBrother: 'Frère germain', paternalBrother: 'Frère consanguin', maternalBrother: 'Frère utérin', nephewFull: 'Neveu germain', nephewPaternal: 'Neveu consanguin', uncleFull: 'Oncle germain', unclePaternal: 'Oncle consanguin', cousinFull: 'Cousin germain', cousinPaternal: 'Cousin consanguin', husband: 'Mari', freedSlaveMale: 'Affranchi (H)', daughter: 'Fille', granddaughter: 'Petite-fille', mother: 'Mère', paternalGrandmother: 'Grand-mère paternelle', maternalGrandmother: 'Grand-mère maternelle', fullSister: 'Sœur germaine', paternalSister: 'Sœur consanguine', maternalSister: 'Sœur utérine', wife: 'Femme', freedSlaveFemale: 'Affranchie (F)', governmentTreasury: 'Trésor Public' },
  es: { son: 'Hijo', grandson: 'Nieto', father: 'Padre', grandfather: 'Abuelo', fullBrother: 'Hermano germano', paternalBrother: 'Hermano consanguíneo', maternalBrother: 'Hermano uterino', nephewFull: 'Sobrino germano', nephewPaternal: 'Sobrino consanguíneo', uncleFull: 'Tío germano', unclePaternal: 'Tío consanguíneo', cousinFull: 'Primo germano', cousinPaternal: 'Primo consanguíneo', husband: 'Esposo', freedSlaveMale: 'Liberto (H)', daughter: 'Hija', granddaughter: 'Nieta', mother: 'Madre', paternalGrandmother: 'Abuela paterna', maternalGrandmother: 'Abuela materna', fullSister: 'Hermana germana', paternalSister: 'Hermana consanguínea', maternalSister: 'Hermana uterina', wife: 'Esposa', freedSlaveFemale: 'Liberta (M)', governmentTreasury: 'Tesoro Público' }
};

const commonStrings: Record<string, any> = {
  en: {
    title: 'Inheritance Calculator', subtitle: 'Al-Farā’iḍ/Mirath', distributionAmount: 'Amount to Divide', funeralExpenses: 'Funeral Expenses', debts: 'Debts', wasiyyat: 'Wasiyyat (UpTo 1/3)', wasiyyatLimit: 'Up to 1/3', currency: 'Currency', fiqhSchool: 'Fiqh School', language: 'Language', deceasedGender: 'Deceased Gender', heirsSelection: 'Select Heirs', calculate: 'Calculate Shares', recalculate: 'Recalculate', reset: 'Start Over', results: 'Results', shareTable: 'Share Table', familyTree: 'Visual Tree', explanation: 'Detailed Explanations', blockedBy: 'Blocked by', male: 'Male', female: 'Female', summary: 'Asset Details', deductions: 'Deductions', noHeirs: 'Please select heirs on the left.', heirTypes: { Sharer: 'Sharer', Residuary: 'Residuary', Blocked: 'Blocked', Treasury: 'Treasury' }, schools: { Hanafi: 'Hanafi', Shafi: 'Shafi‘i', Maliki: 'Maliki', Hanbali: 'Hanbali' }, table: { heir: 'Heir', totalShare: 'Total Share', individualShare: 'Individual Share', totalAmount: 'Total Amount', count: 'Count', each: 'Each', perPerson: 'Per Person Share' }, excludedHeader: 'Excluded Heirs (Hajb)', reasonLabel: 'Reason', statusExcluded: 'Status: Fully Excluded', principleLabel: 'Inheritance Principles', quranRefLabel: 'Quran Reference', exp_blocked: 'Excluded due to higher priority heirs.', exp_no_share: 'No share remaining.', exp_husband_1: '1/2: No descendants.', exp_husband_2: '1/4: Descendants exist.', exp_wife_1: '1/4: No descendants.', exp_wife_2: '1/8: Descendants exist.', exp_son: 'Residuary (2:1).', exp_daughter_1: '1/2: Only daughter.', exp_daughter_2: '2/3: Multiple daughters.', exp_daughter_3: 'Residuary with brother.', exp_father_1: '1/6: Male descendants exist.', exp_father_2: 'Residuary: No male descendants.', exp_mother_1: '1/6: Descendants/siblings exist.', exp_mother_2: '1/3: No descendants/siblings.', exp_general: 'Rule-based share.', exp_treasury: 'No eligible heirs.', netEstateLabel: 'Net Estate for Distribution', totalDeductionsLabel: 'Total Deductions', deceasedLabel: 'Deceased'
  },
  ar: {
    title: 'حاسبة الميراث', subtitle: 'الفرائض والوصايا', distributionAmount: 'المبلغ المراد تقسيمه', funeralExpenses: 'مصاريف الجنازة', debts: 'الديون', wasiyyat: 'الوصية (بحد أقصى الثلث)', wasiyyatLimit: 'بحد أقصى الثلث', currency: 'العملة', fiqhSchool: 'المذهب الفقهي', language: 'اللغة', deceasedGender: 'جنس المتوفى', heirsSelection: 'اختر الورثة', calculate: 'احسب الأنصبة', recalculate: 'إعادة الحساب', reset: 'ابدأ من جديد', results: 'النتائج', shareTable: 'جدول الأنصبة', familyTree: 'شجرة العائلة', explanation: 'شرح مفصل', blockedBy: 'محجوب بـ', male: 'ذكر', female: 'أنثى', summary: 'تفاصيل الأصول', deductions: 'الخصومات', noHeirs: 'يرجى اختيار الورثة من القائمة اليسرى.', heirTypes: { Sharer: 'صاحب فرض', Residuary: 'عصبة', Blocked: 'محجوب', Treasury: 'بيت المال' }, schools: { Hanafi: 'حنفي', Shafi: 'شافعي', Maliki: 'مالكي', Hanbali: 'حنبلي' }, table: { heir: 'الوارث', totalShare: 'النصيب الإجمالي', individualShare: 'نصيب الفرد', totalAmount: 'المبلغ الإجمالي', count: 'العدد', each: 'لكل واحد', perPerson: 'نصيب الفرد الواحد' }, excludedHeader: 'الورثة المحجوبون (حجب)', reasonLabel: 'السبب', statusExcluded: 'الحالة: محجوب بالكامل', principleLabel: 'مبادئ الميراث', quranRefLabel: 'مرجع قرآني', exp_blocked: 'محجوب بسبب وجود ورثة أقرب.', exp_no_share: 'لا يوجد نصيب متبقي.', exp_husband_1: '1/2: لعدم وجود فرع وارث.', exp_husband_2: '1/4: لوجود فرع وارث.', exp_wife_1: '1/4: لعدم وجود فرع وارث.', exp_wife_2: '1/8: لوجود فرع وارث.', exp_son: 'عصبة (للذكر مثل حظ الأنثيين).', exp_daughter_1: '1/2: ابنة واحدة فقط.', exp_daughter_2: '2/3: أكثر من ابنة واحدة.', exp_daughter_3: 'عصبة بالغير مع الأخ.', exp_father_1: '1/6: لوجود فرع وارث ذكر.', exp_father_2: 'عصبة: لعدم وجود فرع وارث ذكر.', exp_mother_1: '1/6: لوجود فرع وارث أو جمع من الإخوة.', exp_mother_2: '1/3: لعدم وجود فرع وارث أو جمع من الإخوة.', exp_general: 'نصيب حسب القواعد الفقهية.', exp_treasury: 'لا يوجد ورثة مؤهلون، يؤول لبيت المال.', netEstateLabel: 'صافي التركة للتوزيع', totalDeductionsLabel: 'إجمالي الخصومات', deceasedLabel: 'المتوفى'
  },
  ur: {
    title: 'وراثت کیلکولیٹر', subtitle: 'الفرائض/میراث', distributionAmount: 'تقسیم کے لیے رقم', funeralExpenses: 'کفن و دفن کے اخراجات', debts: 'قرضے', wasiyyat: 'وصیت (1/3 تک)', wasiyyatLimit: '1/3 تک', currency: 'کرنسی', fiqhSchool: 'فقہی مسلک', language: 'زبان', deceasedGender: 'متوفی کی جنس', heirsSelection: 'وارثین کا انتخاب', calculate: 'حصوں کا حساب', recalculate: 'دوبارہ حساب', reset: 'شروع سے شروع کریں', results: 'نتائج', shareTable: 'حصوں کی تقسیم کا جدول', familyTree: 'خاندانی شجرہ', explanation: 'تفصیلی وضاحت', blockedBy: 'محروم بذریعہ', male: 'مرد', female: 'عورت', summary: 'اثاثوں کی تفصیل', deductions: 'کٹوتیاں', noHeirs: 'براہ کرم بائیں طرف سے وارثین منتخب کریں۔', heirTypes: { Sharer: 'صاحبِ فرض', Residuary: 'عصبہ', Blocked: 'محروم', Treasury: 'بیت المال' }, schools: { Hanafi: 'حنفی', Shafi: 'شافعی', Maliki: 'مالکی', Hanbali: 'حنبلي' }, table: { heir: 'وارث', totalShare: 'کل حصہ', individualShare: 'انفرادی حصہ', totalAmount: 'کل رقم', count: 'تعداد', each: 'ہر ایک', perPerson: 'فی کس حصہ' }, excludedHeader: 'محروم وارثین (حجب)', reasonLabel: 'وجہ', statusExcluded: 'حیثیت: مکمل محروم', principleLabel: 'وراثت کے اصول', quranRefLabel: 'قرآنی حوالہ', exp_blocked: 'قریبی وارثین کی موجودگی کی وجہ سے محروم۔', exp_no_share: 'کوئی حصہ باقی نہیں بچا۔', exp_husband_1: '1/2: کوئی اولاد نہ ہونے کی صورت میں۔', exp_husband_2: '1/4: اولاد ہونے کی صورت میں۔', exp_wife_1: '1/4: کوئی اولاد نہ ہونے کی صورت میں۔', exp_wife_2: '1/8: اولاد ہونے کی صورت میں۔', exp_son: 'عصبہ (2:1)۔', exp_daughter_1: '1/2: صرف ایک بیٹی۔', exp_daughter_2: '2/3: ایک سے زیادہ بیٹیاں۔', exp_daughter_3: 'بھائی کے ساتھ عصبہ۔', exp_father_1: '1/6: نرینہ اولاد کی موجودگی میں۔', exp_father_2: 'عصبہ: نرینہ اولاد نہ ہونے کی صورت میں۔', exp_mother_1: '1/6: اولاد یا بہن بھائیوں کی موجودگی میں۔', exp_mother_2: '1/3: اولاد یا بہن بھائیوں کی عدم موجودگی میں۔', exp_general: 'قواعد پر مبنی حصہ۔', exp_treasury: 'کوئی اہل وارث نہیں، بیت المال میں جائے گا۔', netEstateLabel: 'تقسیم کے لیے خالص ترکہ', totalDeductionsLabel: 'کل کٹوتیاں', deceasedLabel: 'متوفی'
  },
  hi: {
    title: 'विरासत कैलकुलेटर', subtitle: 'अल-फराइज़', distributionAmount: 'विभाजित राशि', funeralExpenses: 'अंतिम संस्कार खर्च', debts: 'कर्ज', wasiyyat: 'वसीयत (1/3 तक)', wasiyyatLimit: '1/3 तक', currency: 'मुद्रा', fiqhSchool: 'फ़िक़्ह स्कूल', language: 'भाषा', deceasedGender: 'मृतक लिंग', heirsSelection: 'वारिस चुनें', calculate: 'गणना करें', recalculate: 'पुनः गणना', reset: 'आरंभ करें', results: 'परिणाम', shareTable: 'हिस्सा तालिका', familyTree: 'पारिवारिक ट्री', explanation: 'विवरण', blockedBy: 'द्वारा वर्जित', male: 'पुरुष', female: 'महिला', summary: 'संपत्ति विवरण', deductions: 'कटौती', noHeirs: 'वारिस चुनें।', heirTypes: { Sharer: 'हिस्सेदार', Residuary: 'अवशेषी', Blocked: 'वर्जित', Treasury: 'राजकोष' }, schools: { Hanafi: 'हनफी', Shafi: 'शाफ़ई', Maliki: 'मालिकी', Hanbali: 'हंबली' }, table: { heir: 'वारिस', totalShare: 'कुल हिस्सा', individualShare: 'व्यक्तिगत हिस्सा', totalAmount: 'कुल राशि', count: 'संख्या', each: 'प्रत्येक', perPerson: 'प्रति व्यक्ति' }, excludedHeader: 'वर्जित वारिस', reasonLabel: 'कारण', statusExcluded: 'पूरी तरह वर्जित', principleLabel: 'विरासत सिद्धांत', quranRefLabel: 'कुरान संदर्भ', exp_blocked: 'उच्च प्राथमिकता वाले वारिस मौजूद हैं।', exp_no_share: 'हिस्सा समाप्त।', exp_husband_1: '1/2: कोई वंशज नहीं।', exp_husband_2: '1/4: वंशज मौजूद हैं।', exp_wife_1: '1/4: कोई वंशज नहीं।', exp_wife_2: '1/8: वंशज मौजूद हैं।', exp_son: 'अवशेषी (2:1)।', exp_daughter_1: '1/2: इकलौती बेटी।', exp_daughter_2: '2/3: अनेक बेटियाँ।', exp_daughter_3: 'भाई के साथ अवशेषी।', exp_father_1: '1/6: पुरुष वंशज मौजूद।', exp_father_2: 'अवशेषी: पुरुष वंशज नहीं।', exp_mother_1: '1/6: वंशज मौजूद।', exp_mother_2: '1/3: कोई वंशज नहीं।', exp_general: 'नियम आधारित हिस्सा।', exp_treasury: 'सरकारी खजाने में।', netEstateLabel: 'वितरण राशि', totalDeductionsLabel: 'कुल कटौती', deceasedLabel: 'मृतक'
  },
  bn: {
    title: 'উত্তরাধিকার ক্যালকুলেটর', subtitle: 'আল-ফরায়েজ', distributionAmount: 'বিভাজ্য সম্পদ', funeralExpenses: 'দাফন খরচ', debts: 'ঋণ', wasiyyat: 'ওসিয়ত (১/৩ পর্যন্ত)', wasiyyatLimit: '১/৩ পর্যন্ত', currency: 'কারেন্সি', fiqhSchool: 'মাযহাব', language: 'ভাষা', deceasedGender: 'মৃতের লিঙ্গ', heirsSelection: 'ওয়ারিশ নির্বাচন', calculate: 'হিসাব করুন', recalculate: 'পুনরায় হিসাব', reset: 'শুরু থেকে', results: 'ফলাফল', shareTable: 'বন্টন তালিকা', familyTree: 'বংশবৃক্ষ', explanation: 'বিস্তারিত ব্যাখ্যা', blockedBy: 'দ্বারা বঞ্চিত', male: 'পুরুষ', female: 'নারী', summary: 'সম্পদ বিবরণ', deductions: 'খরচসমূহ', noHeirs: 'ওয়ারিশ নির্বাচন করুন।', heirTypes: { Sharer: 'অংশীদার', Residuary: 'অবশিষ্টাংশভোগী', Blocked: 'বঞ্চিত', Treasury: 'বাইতুল মাল' }, schools: { Hanafi: 'হানাফী', Shafi: 'শাফেয়ী', Maliki: 'মালিকী', Hanbali: 'হাম্বলী' }, table: { heir: 'ওয়ারিশ', totalShare: 'মোট অংশ', individualShare: 'ব্যগত অংশ', totalAmount: 'মোট টাকা', count: 'সংখ্যা', each: 'প্রতিটি', perPerson: 'মাথাপিছু অংশ' }, excludedHeader: 'বঞ্চিত ওয়ারিশগণ', reasonLabel: 'কারণ', statusExcluded: 'সম্পূর্ণ বঞ্চিত', principleLabel: 'নীতিমালা', quranRefLabel: 'কুরআন রেফারেন্স', exp_blocked: 'উচ্চ অগ্রাধিকার ওয়ারিশ উপস্থিত।', exp_no_share: 'অংশ অবশিষ্ট নেই।', exp_husband_1: '১/২: সন্তান নেই।', exp_husband_2: '১/৪: সন্তান আছে।', exp_wife_1: '১/৪: সন্তান নেই।', exp_wife_2: '১/৮: সন্তান আছে।', exp_son: 'আসাবা (২:১)।', exp_daughter_1: '১/২: একমাত্র কন্যা।', exp_daughter_2: '২/৩: একাধিক কন্যা।', exp_daughter_3: 'ভাইয়ের সাথে আসাবা।', exp_father_1: '১/৬: বংশধর আছে।', exp_father_2: 'আসাবা: বংশধর নেই।', exp_mother_1: '১/৬: সন্তান/ভাইবোন আছে।', exp_mother_2: '১/৩: সন্তান/ভাইবোন নেই।', exp_general: 'শরীয়াহ সম্মত অংশ।', exp_treasury: 'বাইতুল মালে স্থানান্তরিত।', netEstateLabel: 'বন্টনযোগ্য সম্পদ', totalDeductionsLabel: 'মোট খরচ', deceasedLabel: 'মৃত ব্যক্তি'
  },
  tr: {
    title: 'Miras Hesaplayıcı', subtitle: 'el-Feraiz', distributionAmount: 'Dağıtılacak Tutar', funeralExpenses: 'Cenaze Masrafı', debts: 'Borçlar', wasiyyat: 'Vasiyet (1/3\'e Kadar)', wasiyyatLimit: '1/3\'e Kadar', currency: 'Para Birimi', fiqhSchool: 'Mezhep', language: 'Dil', deceasedGender: 'Vefat Eden Cinsiyeti', heirsSelection: 'Varis Seçimi', calculate: 'Hesapla', recalculate: 'Yeniden Hesapla', reset: 'Sıfırla', results: 'Sonuçlar', shareTable: 'Pay Tablosu', familyTree: 'Soyağacı', explanation: 'Detaylı Açıklama', blockedBy: 'Tarafından Engellendi', male: 'Erkek', female: 'Kadın', summary: 'Varlık Detayları', deductions: 'Kesintiler', noHeirs: 'Lütfen varis seçin.', heirTypes: { Sharer: 'Hissedar', Residuary: 'Asabe', Blocked: 'Mahcup', Treasury: 'Beytülmal' }, schools: { Hanafi: 'Hanefi', Shafi: 'Şafii', Maliki: 'Maliki', Hanbali: 'Hanbeli' }, table: { heir: 'Varis', totalShare: 'Toplam Pay', individualShare: 'Kişi Başı', totalAmount: 'Toplam Tutar', count: 'Sayı', each: 'Her biri', perPerson: 'Kişi başı hisse' }, excludedHeader: 'Dışlanan Varisler', reasonLabel: 'Neden', statusExcluded: 'Tamamen Dışlanmış', principleLabel: 'Miras İlkeleri', quranRefLabel: 'Kur\'an Referansı', exp_blocked: 'Öncelikli varisler nedeniyle dışlanmış.', exp_no_share: 'Pay kalmadı.', exp_husband_1: '1/2: Çocuk yok.', exp_husband_2: '1/4: Çocuk var.', exp_wife_1: '1/4: Çocuk yok.', exp_wife_2: '1/8: Çocuk var.', exp_son: 'Asabe (2:1).', exp_daughter_1: '1/2: Tek kız.', exp_daughter_2: '2/3: Birden fazla kız.', exp_daughter_3: 'Erkek kardeşle asabe.', exp_father_1: '1/6: Erkek çocuk var.', exp_father_2: 'Asabe: Erkek çocuk yok.', exp_mother_1: '1/6: Çocuk/kardeş var.', exp_mother_2: '1/3: Çocuk/kardeş yok.', exp_general: 'Fıkhi kurala göre pay.', exp_treasury: 'Varis bulunamadı.', netEstateLabel: 'Net Miras', totalDeductionsLabel: 'Toplam Kesinti', deceasedLabel: 'Vefat Eden'
  },
  id: {
    title: 'Kalkulator Waris', subtitle: 'Al-Farā’iḍ', distributionAmount: 'Total Harta', funeralExpenses: 'Biaya Jenazah', debts: 'Hutang', wasiyyat: 'Wasiat (Maks 1/3)', wasiyyatLimit: 'Maks 1/3', currency: 'Mata Uang', fiqhSchool: 'Madzhab', language: 'Bahasa', deceasedGender: 'Jenis Kelamin Mayit', heirsSelection: 'Pilih Ahli Waris', calculate: 'Hitung Waris', recalculate: 'Hitung Ulang', reset: 'Mulai Baru', results: 'Hasil', shareTable: 'Tabel Bagian', familyTree: 'Pohon Visual', explanation: 'Penjelasan Detail', blockedBy: 'Terhalang oleh', male: 'Laki-laki', female: 'Perempuan', summary: 'Detail Aset', deductions: 'Potongan', noHeirs: 'Pilih ahli waris.', heirTypes: { Sharer: 'Ahli Waris Utama', Residuary: 'Ashabah', Blocked: 'Terhalang', Treasury: 'Baitul Maal' }, schools: { Hanafi: 'Hanafi', Shafi: 'Syafi\'i', Maliki: 'Maliki', Hanbali: 'Hambali' }, table: { heir: 'Ahli Waris', totalShare: 'Total Bagian', individualShare: 'Bagian Per Orang', totalAmount: 'Total Nilai', count: 'Jumlah', each: 'Masing-masing', perPerson: 'Bagian Per Jiwa' }, excludedHeader: 'Ahli Waris Terhijab', reasonLabel: 'Alasan', statusExcluded: 'Status: Terhijab Penuh', principleLabel: 'Prinsip Waris', quranRefLabel: 'Referensi Al-Quran', exp_blocked: 'Terhijab oleh ahli waris yang lebih dekat.', exp_no_share: 'Harta habis terbagi.', exp_husband_1: '1/2: Tidak ada keturunan.', exp_husband_2: '1/4: Ada keturunan.', exp_wife_1: '1/4: Tidak ada keturunan.', exp_wife_2: '1/8: Ada keturunan.', exp_son: 'Ashabah (2:1).', exp_daughter_1: '1/2: Anak tunggal.', exp_daughter_2: '2/3: Lebih dari satu anak.', exp_daughter_3: 'Ashabah bersama saudara laki-laki.', exp_father_1: '1/6: Ada keturunan laki-laki.', exp_father_2: 'Ashabah: Tidak ada keturunan laki-laki.', exp_mother_1: '1/6: Ada keturunan/saudara.', exp_mother_2: '1/3: Tidak ada keturunan/saudara.', exp_general: 'Bagian sesuai kaidah.', exp_treasury: 'Diserahkan ke Baitul Maal.', netEstateLabel: 'Netto Warisan', totalDeductionsLabel: 'Total Potongan', deceasedLabel: 'Jenazah'
  },
  fr: {
    title: 'Calculateur d\'Héritage', subtitle: 'Al-Farā’iḍ', distributionAmount: 'Montant à Diviser', funeralExpenses: 'Frais Funéraires', debts: 'Dettes', wasiyyat: 'Wasiyyat (Max 1/3)', wasiyyatLimit: 'Max 1/3', currency: 'Devise', fiqhSchool: 'École Juridique', language: 'Langue', deceasedGender: 'Sexe du Défunt', heirsSelection: 'Sélection des Héritiers', calculate: 'Calculer', recalculate: 'Recalculer', reset: 'Réinitialiser', results: 'Résultats', shareTable: 'Tableau des Parts', familyTree: 'Arbre Visuel', explanation: 'Explications Détaillées', blockedBy: 'Exclu par', male: 'Homme', female: 'Femme', summary: 'Détails des Actifs', deductions: 'Déductions', noHeirs: 'Veuillez choisir les héritiers.', heirTypes: { Sharer: 'Fixe', Residuary: 'Residuel', Blocked: 'Exclu', Treasury: 'Trésor' }, schools: { Hanafi: 'Hanafite', Shafi: 'Chaféite', Maliki: 'Malikite', Hanbali: 'Hanbalite' }, table: { heir: 'Héritier', totalShare: 'Part Totale', individualShare: 'Part Indiv.', totalAmount: 'Total', count: 'Nombre', each: 'Chaque', perPerson: 'Part par personne' }, excludedHeader: 'Héritiers Exclus', reasonLabel: 'Raison', statusExcluded: 'Statut : Entièrement Exclu', principleLabel: 'Principes', quranRefLabel: 'Réf. Coranique', exp_blocked: 'Exclu par des héritiers prioritaires.', exp_no_share: 'Patrimoine épuisé.', exp_husband_1: '1/2 : Pas de descendants.', exp_husband_2: '1/4 : Descendants.', exp_wife_1: '1/4 : Pas de descendants.', exp_wife_2: '1/8 : Descendants.', exp_son: 'Asaba (2:1).', exp_daughter_1: '1/2 : Fille unique.', exp_daughter_2: '2/3 : Plusieurs filles.', exp_daughter_3: 'Asaba avec le frère.', exp_father_1: '1/6 : Descendants mâles.', exp_father_2: 'Asaba : Pas de descendants mâles.', exp_mother_1: '1/6 : Descendants/fratrie.', exp_mother_2: '1/3 : Pas de descendants/fratrie.', exp_general: 'Part standard.', exp_treasury: 'Transféré au Trésor.', netEstateLabel: 'Héritage Net', totalDeductionsLabel: 'Total des Déductions', deceasedLabel: 'Défunt'
  },
  es: {
    title: 'Calculadora de Herencia', subtitle: 'Al-Farā’iḍ', distributionAmount: 'Monto a Dividir', funeralExpenses: 'Gastos Funerarios', debts: 'Deudas', wasiyyat: 'Wasiyyat (Hasta 1/3)', wasiyyatLimit: 'Hasta 1/3', currency: 'Moneda', fiqhSchool: 'Escuela Jurídica', language: 'Idioma', deceasedGender: 'Género del Difunto', heirsSelection: 'Seleccionar Herederos', calculate: 'Calcular', recalculate: 'Recalcular', reset: 'Reiniciar', results: 'Resultados', shareTable: 'Tabla de Reparto', familyTree: 'Árbol Visual', explanation: 'Detalles', blockedBy: 'Excluido por', male: 'Hombre', female: 'Mujer', summary: 'Activos', deductions: 'Deducciones', noHeirs: 'Seleccione herederos.', heirTypes: { Sharer: 'Fijo', Residuary: 'Residuo', Blocked: 'Excluido', Treasury: 'Tesoro' }, schools: { Hanafi: 'Hanafí', Shafi: 'Shafi\'í', Maliki: 'Malikí', Hanbali: 'Hanbalí' }, table: { heir: 'Heredero', totalShare: 'Cuota Total', individualShare: 'Cuota Indiv.', totalAmount: 'Monto Total', count: 'Cantidad', each: 'Cada uno', perPerson: 'Por persona' }, excludedHeader: 'Herederos Excluidos', reasonLabel: 'Razón', statusExcluded: 'Totalmente Excluido', principleLabel: 'Principios', quranRefLabel: 'Ref. Coránica', exp_blocked: 'Excluido por prioridad.', exp_no_share: 'Patrimonio agotado.', exp_husband_1: '1/2: Sin descendientes.', exp_husband_2: '1/4: Con descendientes.', exp_wife_1: '1/4: Sin descendientes.', exp_wife_2: '1/8: Con descendientes.', exp_son: 'Asaba (2:1).', exp_daughter_1: '1/2: Hija única.', exp_daughter_2: '2/3: Varias hijas.', exp_daughter_3: 'Asaba con hermano.', exp_father_1: '1/6: Descendientes varones.', exp_father_2: 'Asaba: Sin descendientes varones.', exp_mother_1: '1/6: Descendientes/hermanos.', exp_mother_2: '1/3: Sin descendientes/hermanos.', exp_general: 'Cuota estándar.', exp_treasury: 'Al Tesoro Público.', netEstateLabel: 'Herencia Neta', totalDeductionsLabel: 'Total Deducciones', deceasedLabel: 'Difunto'
  }
};

const currencyNames: Record<string, Record<string, string>> = {
  en: { USD: 'US Dollar', EUR: 'Euro', GBP: 'British Pound', SAR: 'Saudi Riyal', AED: 'UAE Dirham', PKR: 'Pakistani Rupee', INR: 'Indian Rupee', TRY: 'Turkish Lira', IDR: 'Indonesian Rupiah', MYR: 'Malaysian Ringgit', EGP: 'Egyptian Pound', KWD: 'Kuwaiti Dinar', QAR: 'Qatari Riyal', BDT: 'Bangladeshi Taka', NGN: 'Nigerian Naira', ZAR: 'South African Rand', CAD: 'Canadian Dollar', AUD: 'Australian Dollar', JPY: 'Japanese Yen', CNY: 'Chinese Yuan' },
  ar: { USD: 'دولار أمريكي', EUR: 'يورو', GBP: 'جنيه إسترليني', SAR: 'ريال سعودي', AED: 'درهم إماراتي', PKR: 'روبية باكستانية', INR: 'روبية هندية', TRY: 'ليرة تركية', IDR: 'روبية إندونيسية', MYR: 'رينغيت ماليزي', EGP: 'جنيه مصري', KWD: 'دينار كويتي', QAR: 'ريال قطري', BDT: 'تاكا بنغلاديشي', NGN: 'نايرا نيجيري', ZAR: 'راند جنوب أفريقي', CAD: 'دولار كندي', AUD: 'دولار أسترالي', JPY: 'ين ياباني', CNY: 'يوان صيني' },
  ur: { USD: 'امریکی ڈالر', EUR: 'یورو', GBP: 'برطانوی پاؤنڈ', SAR: 'سعودی ریال', AED: 'متحدہ عرب امارات درہم', PKR: 'پاکستانی روپیہ', INR: 'بھارتی روپیہ', TRY: 'ترک لیرا', IDR: 'انڈونیشیائی روپیہ', MYR: 'ملائیشین رنگٹ', EGP: 'مصری پاؤنڈ', KWD: 'کویتی دینار', QAR: 'قطری ریال', BDT: 'بنگلہ دیشی ٹکا', NGN: 'نائجیرین نائرا', ZAR: 'جنوبی افریقي رانڈ', CAD: 'کینیڈین ڈالر', AUD: 'آسٹریلوی ڈالر', JPY: 'جاپانی ین', CNY: 'چینی یوآن' },
  hi: { USD: 'अमेरिकी डॉलर', EUR: 'यूरो', GBP: 'ब्रिटिश पाउंड', SAR: 'सऊदी रियाल', AED: 'संयुक्त अरब अमीरात दिरहम', PKR: 'पाकिस्तानी रुपया', INR: 'भारतीय रुपया', TRY: 'तुर्की लीरा', IDR: 'इंडोनेशियाई रुपिया', MYR: 'मलेशियाई रिंगिट', EGP: 'मिस्र पाउंड', KWD: 'कुवैती दीनार', QAR: 'कतारी रियाल', BDT: 'बांग्लादेशी टका', NGN: 'नाइजीरियाई नायरा', ZAR: 'दक्षिण अफ्रीकी रैंड', CAD: 'कनाडाई डॉलर', AUD: 'ऑस्ट्रेलियाई डॉलर', JPY: 'जापानी येन', CNY: 'चीनी युआन' },
  bn: { USD: 'মার্কিন ডলার', EUR: 'ইউরো', GBP: 'ব্রিটিশ পাউন্ড', SAR: 'সৌদি রিয়াল', AED: 'সংযুক্ত আরব আমিরাত দিরহাম', PKR: 'পাকিস্তানি রুপি', INR: 'ভারতীয় রুপি', TRY: 'তুর্কি লিরা', IDR: 'ইন্দোনেশীয় রুপিয়াহ', MYR: 'মালয়েশীয় রিঙ্গিত', EGP: 'মিশরীয় পাউন্ড', KWD: 'কুয়েতি দিনার', QAR: 'কাতারি রিয়াল', BDT: 'বাংলাদেশী টাকা', NGN: 'নাইজেরিয়ান নাইরা', ZAR: 'দক্ষিণ আফ্রিকান র‍্যান্ড', CAD: 'কানাডিয়ান ডলার', AUD: 'অস্ট্রেলিয়ান ডলার', JPY: 'জাপানি ইয়েন', CNY: 'চীনা ইউয়ান' },
  tr: { USD: 'ABD Doları', EUR: 'Euro', GBP: 'İngiliz Sterlini', SAR: 'Suudi Riyali', AED: 'BAE Dirhemi', PKR: 'Pakistan Rupisi', INR: 'Hint Rupisi', TRY: 'Türk Lirası', IDR: 'Endonezya Rupisi', MYR: 'Malezya Ringgiti', EGP: 'Mısır Lirası', KWD: 'Kuveyt Dinarı', QAR: 'Katar Riyali', BDT: 'Bangladeş Takası', NGN: 'Nijerya Nairası', ZAR: 'Güney Afrika Randı', CAD: 'Kanada Doları', AUD: 'Avustralya Doları', JPY: 'Japon Yeni', CNY: 'Çin Yuanı' },
  id: { USD: 'Dolar AS', EUR: 'Euro', GBP: 'Pound Sterling', SAR: 'Riyal Saudi', AED: 'Dirham UEA', PKR: 'Rupee Pakistan', INR: 'Rupee India', TRY: 'Lira Turki', IDR: 'Rupiah Indonesia', MYR: 'Ringgit Malaysia', EGP: 'Pound Mesir', KWD: 'Dinar Kuwait', QAR: 'Riyal Qatar', BDT: 'Taka Bangladesh', NGN: 'Naira Nigeria', ZAR: 'Rand Afrika Selatan', CAD: 'Dolar Kanada', AUD: 'Dolar Australia', JPY: 'Yen Jepang', CNY: 'Yuan Tiongkok' },
  fr: { USD: 'Dollar américain', EUR: 'Euro', GBP: 'Livre sterling', SAR: 'Riyal saoudien', AED: 'Dirham des EAU', PKR: 'Roupie pakistanaise', INR: 'Roupie indienne', TRY: 'Lire turque', IDR: 'Roupie indonésienne', MYR: 'Ringgit malaisien', EGP: 'Livre égyptienne', KWD: 'Dinar koweïtien', QAR: 'Riyal qatarien', BDT: 'Taka bangladais', NGN: 'Naira nigérian', ZAR: 'Rand sud-africain', CAD: 'Dollar canadien', AUD: 'Dollar australien', JPY: 'Yen japonais', CNY: 'Yuan chinois' },
  es: { USD: 'Dólar estadounidense', EUR: 'Euro', GBP: 'Libra esterlina', SAR: 'Riyal saudí', AED: 'Dirham de los EAU', PKR: 'Rupia paquistaní', INR: 'Rupia india', TRY: 'Lira turca', IDR: 'Rupia indonesia', MYR: 'Ringgit malayo', EGP: 'Libra egipcia', KWD: 'Dinar kuwaití', QAR: 'Riyal catarí', BDT: 'Taka de Bangladesh', NGN: 'Naira nigeriana', ZAR: 'Rand sudafricano', CAD: 'Dólar canadiense', AUD: 'Dólar australiano', JPY: 'Yen japonés', CNY: 'Yuan chino' }
};

// Merge all translations
export const i18nStrings: Record<string, any> = {
  ...commonStrings,
  en: { ...commonStrings.en, heirs: heirTranslations.en, currencies: currencyNames.en || {} },
  ar: { ...commonStrings.ar, heirs: heirTranslations.ar, currencies: currencyNames.ar || {} },
  ur: { ...commonStrings.ur, heirs: heirTranslations.ur, currencies: currencyNames.ur || {} },
  hi: { ...commonStrings.hi, heirs: heirTranslations.hi, currencies: currencyNames.hi || {} },
  bn: { ...commonStrings.bn, heirs: heirTranslations.bn, currencies: currencyNames.bn || {} },
  tr: { ...commonStrings.tr, heirs: heirTranslations.tr, currencies: currencyNames.tr || {} },
  id: { ...commonStrings.id, heirs: heirTranslations.id, currencies: currencyNames.id || {} },
  fr: { ...commonStrings.fr, heirs: heirTranslations.fr, currencies: currencyNames.fr || {} },
  es: { ...commonStrings.es, heirs: heirTranslations.es, currencies: currencyNames.es || {} },
};
